server:
  host: "192.168.58.9"
  port: 1883
  seed: 2024
  num_rounds: 30
  num_clients: 10
  strategy: Local #FedAvg, Local
  method: FedAvg # FedAvg, FedSCP
  cluster: AffinityPropagation

client:
  ID: "0"
  host: "192.168.58.9"
  strategy: Local #FedAvg, Local
  num_epochs: 1

data:
  dataset: Cifar10 # dga_data, dga_data_binary, Cifar10, Cifar100, FashionMNIST
  download: False
  argumentation: 0
  drop_last: True # if dataloader is not divisible by batch_size
  data_for_client_train: \data\sperated_data_client\train
  data_for_client_test: \data\sperated_data_client\test
  num_classes: 10 # 11 if dga_data | 1 if dga_data_binary | images data
  partition: noniid_label_distribution # iid_equal_size, iid_diff_size, noniid_label_quantity, noniid_label_distribution
  data_volume_each_client: equal
  beta: 0.7
  rho: 0.9
  logger: False

model:
  model_run: Lenet # Lenet,  BiLSTM, LSTMModel
  # optimizer: SGD
  # criterion: ss
  batch_size: 32 # 19, 64 for LSTM & 32 for images
  lr: 2e-5

  # for LSTM Model
  max_features: 101  # max_features = number of one-hot dimensions
  embed_size: 64
  hidden_size: 64
  n_layers: 1

logger:
  show: False