server:
  host: "192.168.1.119"
  port: 1883
  seed: 2024
  num_rounds: 3
  num_clients: 1
  strategy: FedAvg


client:
  ID: "0"
  host: "192.168.1.119"
  strategy: FedAvg
  model: LSTMModel # LeNet,  BiLSTM, LSTMModel
  # optimizer: SGD
  # criterion: ss
  num_epochs: 1
  batch_size: 19 # 19, 64 for LSTM & 32 for images
  lr: 2e-5
  drop_last: True # if dataloader is not divisible by batch_size

  dataset: dga_data # dga_data, dga_data_binary, Cifar10, Cifar100, FashionMNIST
  data_for_client_train: \data\sperated_data_client\train
  data_for_client_test: \data\sperated_data_client\test
  num_classes: 11 # 11 if dga_data | 1 if dga_data_binary | images data
  partition: iid_equal_size # iid_equal_size, iid_diff_size, noniid_label_quantity, noniid_label_distribution
  data_volume_each_client: equal
  beta: 0.7
  rho: 0.9

  # for LSTM Model
  max_features: 101  # max_features = number of one-hot dimensions
  embed_size: 64
  hidden_size: 64
  n_layers: 1
